$(document).bind('mobileinit',function(){
  $.mobile.changePage.defaults.changeHash = false;
  $.mobile.hashListeningEnabled = false;
  $.mobile.pushStateEnabled = false;
});

const observer = lozad('.lozad', { rootMargin: '10px 0px', threshold: 0.1 });
const Installer = function(root) {
  let promptEvent;

  const install = function(e) {
    if(promptEvent) {
      promptEvent.prompt();
      promptEvent.userChoice
        .then(function(choiceResult) {
          // The user actioned the prompt (good or bad).
          // good is handled in
          promptEvent = null;
          // ga('send', 'event', 'install', choiceResult);
          root.classList.remove('available');
        })
        .catch(function(installError) {
          // Boo. update the UI.
          promptEvent = null;
          // ga('send', 'event', 'install', 'errored');
          root.classList.remove('available');
        });
    }
  };

  const installed = function(e) {
    promptEvent = null;
    // This fires after onbeforinstallprompt OR after manual add to homescreen.
    // ga('send', 'event', 'install', 'installed');
    root.classList.remove('available');
    root.classList.add('hide');
    console.log('installed');
  };

  const beforeinstallprompt = function(e) {
    promptEvent = e;
    promptEvent.preventDefault();
    // ga('send', 'event', 'install', 'available');
    root.classList.add('available');
    return false;
  };

  window.addEventListener('beforeinstallprompt', beforeinstallprompt);
  // window.addEventListener('appinstalled', installed);
  window.addEventListener('appinstalled', (evt) => {
    console.log('installata');
    root.classList.add('install');
  });

  root.addEventListener('click', install.bind(this));
  root.addEventListener('touchend', install.bind(this));
};


window.addEventListener('load', function() {
  if (localStorage.disclaimer && localStorage.go) {
    $("#splash-content").remove()
    $("#map-page").fadeIn(500, initMap)
  }
  const installEl = document.getElementById('installer');
  const installer = new Installer(installEl);
})

if ('serviceWorker' in navigator) {
  window.addEventListener('load', function() {
    navigator.serviceWorker.register('sw.js').then(function(registration) {
      console.log('ServiceWorker registration successful with scope: ', registration.scope);
    }, function(err) {
      console.log('ServiceWorker registration failed: ', err);
    });
  });
}

window.addEventListener("orientationchange", function() {
  window.setTimeout(function() {
    setHeightDiv()
    $("video").css("width",$('.poi-content').width())
    setGalleryDim()
    checkDim()
  }, 200);
}, false);


$(document).ready(function() {
  $("[name=disclaimer]").on('click', function(){
    localStorage.setItem("disclaimer","ok")
    $(".blk1").fadeOut(500, function(){
      $(this).remove()
      $(".blk2").fadeIn(500)
    })
  })
  $("[name=okGo]").on('click', function(){
    localStorage.setItem("go","ok")
    $("#splash-content").fadeOut(500, function(){
      $(this).remove()
      $("#map-page").fadeIn(500, initMap)
    })
  })
  $("body").on('click', '#wrapImage', function(event) {
    $("#wrapImage").toggleClass('flex hide');
  });
});

function checkDim(){
  console.log(screen.width+" "+screen.height);
  if(screen.width > screen.height){
    $(".imgContent").css({"width":"70vw","height":"95vh"})
  }else {
    $(".imgContent").css({"width":"95vw","height":"auto"})
  }
}

function initMap(){
  let punti;
  let sentieri;
  map = new L.Map('map', { minZoom: 13 }).setView([46.1220, 11.1876], 13);
  lyr = L.tileLayer('map/basemap/{z}/{x}/{y}.png', {tms: true, opacity: 0.7, attribution: 'base map tiles generated by <a href="http://www.klokan.cz/projects/gdal2tiles/">GDAL2Tiles</a>'}).addTo(map);

  legend = L.Control.extend({
    options: { position: 'topright'},
    onAdd: function (map) {
      var container = L.DomUtil.create('div', 'legend');
      title = $("<p/>",{class:'p-0 mb-1 border-bottom'}).html("<span class='pr-3'>Sentieri</span>")
      .appendTo(container)
      .on('click', function(){
        list.slideToggle(250)
        $(this).find('i').toggleClass('flip');
      })
      $("<i/>",{class:'fas fa-angle-up fa-lg float-right animation'}).appendTo(title)
      list = $("<ul/>",{id:'sentieri-legend'}).appendTo(container);
      return container;
    }
  })
  startView = L.Control.extend({
    options: { position: 'topleft'},
    onAdd: function (map) {
      var container = L.DomUtil.create('div', 'extentControl leaflet-bar leaflet-control leaflet-touch');
      btn=$("<a/>",{href:'#'}).appendTo(container);
      $("<i/>",{class:'fas fa-home'}).appendTo(btn)
      btn.on('click', function () {map.fitBounds(punti.getBounds());});
      return container;
    }
  })

  map.addControl(new legend());
  map.addControl(new startView());

  $.getJSON('json/punti.geojson',function (data) {
    if (!data.features) {
      map.setView(new L.LatLng(46.1220, 11.1876), 13);
    }else {
      punti = L.geoJSON(data).addTo(map).on('click',slidePanel);
      map.fitBounds(punti.getBounds());
    }
  });

  $.getJSON('json/sentieri.geojson',function (data) {
    $.each(data.features, function(i,v){
      p = v.properties
      li = $("<li/>",{text:p.nome+" ("+p.km+" km.)"}).appendTo('#sentieri-legend')
      $("<i/>",{class:'fas fa-minus fa-lg pr-2'}).css("color",p.color).prependTo(li)
    })
    sentieri = L.geoJSON(data,{
      style: function(feature) { return {color: feature.properties.color,weight:5} }
    }).addTo(map).on('click',slideTrackInfo);
  });

  map.setMaxBounds(map.getBounds());
}
function slidePanel(e){
  prop = e.layer.feature.properties
  setHeightDiv()
  $(".closePanel>h5").html(prop.nome)
  $(".poi-banner").css("background-image","url('img/poi/banner/"+prop.banner+"')")
  content = $(".poi-content").html(prop.desc)
  $('#wrapPoiInfo').fadeIn(500)
  $("body").on('click', '.closePanel', function() { $('#wrapPoiInfo').fadeOut(500); });
  if(prop.slider) {initSlider(e.layer.feature.properties.slider)}
  if(prop.slider2) {beforeAfter(e.layer.feature.properties.slider)}
  if(prop.video){initVideo(e.layer.feature.properties.video)}
  if(prop.tredhop){init3dhop(e.layer.feature.properties.tredhop)}
  if(prop.galleria){initGallery(e.layer.feature.properties.galleria)}
}

function setHeightDiv(){
  $("#wrapPoiInfo").css("bottom","0")
  $(".poiContentDiv").css("height",$('#wrapPoiInfo').height()-50)
}

function init3dhop(url){
  let div = $("<div/>",{id:'3dhopWrap',class:'my-3'}).appendTo('.poi-content')
  $("<a/>",{class:'btn btn-success d-block', href:'3dhop/'+url+'/start.html', text:'visualizza 3d'}).appendTo(div)
}

function initVideo(video){
  var videoDiv=''
  videoDiv+="<div class='video-content'>";
  videoDiv+="<video width='100%' controls>"
  videoDiv+="<source src='video/"+video+"' type='video/mp4'>"
  videoDiv+="Your browser does not support HTML5 video."
  videoDiv+="</video>"
  videoDiv+='</div>'
  $('#videoContent').html(videoDiv)
}

function initGallery(gallery){
  let dir = "img/gallerie/"+gallery.dir;
  let galleryContent = "<div id='galleryContent'></div>";
  $('.poi-content').html($('.poi-content').html().replace('*GALLERIA*',galleryContent));
  let wrap = $("<div/>",{id:'galleryWrap', class:'container-fluid my-3'}).appendTo('#galleryContent')
  let rowImage = $("<div/>",{class:'row mb-2'}).appendTo(wrap)
  $.each(gallery.foto, function(i,v){ $("<div/>", {id:"img"+i,class:'imgCover lozad col-4 col-md-3 border border-white'})
    .attr("data-background-image",dir+"/small/"+v)
    .appendTo(rowImage)
    .on('click', function(){
      $("#wrapImage").toggleClass('hide flex')
      $("#galleryImageLarge").attr("src",dir+"/large/"+v)
      checkDim()
    })
  })
  setGalleryDim()
  observer.observe();
}
function setGalleryDim(){ $("#galleryWrap .lozad").height($("#img0").width()) }

function initSlider(slider){
  sliderDiv  = '<div id="'+slider.id+'" class="js-img-compare">';
  sliderDiv += '<div style="display: none;">';
  sliderDiv += '<span class="images-compare-label">'+slider.bgLabel+'</span>';
  sliderDiv += '<img src="img/poi/slider/'+slider.bgImg+'" alt="'+slider.bgLabel+'">';
  sliderDiv += '</div>';
  sliderDiv += '<div>';
  sliderDiv += '<span class="images-compare-label">'+slider.frontLabel+'</span>';
  sliderDiv += '<img src="img/poi/slider/'+slider.frontImg+'" alt="'+slider.frontLabel+'">';
  sliderDiv += '</div>';
  sliderDiv += '</div>';
  $('#sliderContent').html(sliderDiv);
  var imagesCompareElement = $('.js-img-compare').imagesCompare();
  var imagesCompare = imagesCompareElement.data('imagesCompare');
  var events = imagesCompare.events();
  imagesCompare.on(events.initialised, function (event) {
    console.log(events.initialised);
  });
}

function slideTrackInfo(e){
  prop = e.layer.feature.properties
  $(".closeTrackPanel>h5").html(prop.nome)
  $(".track-banner").css("background-image","url('img/sentieri/banner/"+prop.banner+"')")
  $('#wrapTrackInfo').fadeIn(500)
  $("body").on('click', '.closeTrackPanel', function() { $('#wrapTrackInfo').fadeOut(500); });
}
