$(document).bind('mobileinit',function(){
  $.mobile.changePage.defaults.changeHash = false;
  $.mobile.hashListeningEnabled = false;
  $.mobile.pushStateEnabled = false;
});
window.addEventListener('load', function() {
  if (localStorage.disclaimer && localStorage.go) {
    $("#splash-content").remove()
    $("#map-page").fadeIn(500, initMap)
  }
})
if ('serviceWorker' in navigator) {
  window.addEventListener('load', function() {
    navigator.serviceWorker.register('sw.js').then(function(registration) {
      console.log('ServiceWorker registration successful with scope: ', registration.scope);
    }, function(err) {
      console.log('ServiceWorker registration failed: ', err);
    });
  });
}
$(document).ready(function() {
  $("[name=disclaimer]").on('click', function(){
    localStorage.setItem("disclaimer","ok")
    $(".blk1").fadeOut(500, function(){
      $(this).remove()
      $(".blk2").fadeIn(500)
    })
  })
  $("[name=okGo]").on('click', function(){
    localStorage.setItem("go","ok")
    $("#splash-content").fadeOut(500, function(){
      $(this).remove()
      $("#map-page").fadeIn(500, initMap)
    })
  })
});

function initMap(){
  let punti;
  let sentieri;
  map = new L.Map('map', { minZoom: 13 }).setView([46.1220, 11.1876], 13);
  lyr = L.tileLayer('map/basemap/{z}/{x}/{y}.png', {tms: true, opacity: 0.7, attribution: 'base map tiles generated by <a href="http://www.klokan.cz/projects/gdal2tiles/">GDAL2Tiles</a>'}).addTo(map);

  legend = L.Control.extend({
    options: { position: 'topright'},
    onAdd: function (map) {
      var container = L.DomUtil.create('div', 'legend');
      title = $("<p/>",{text:'Sentieri', class:'p-0 mb-1 border-bottom'})
      .appendTo(container)
      .on('click', function(){
        list.slideToggle(250)
        $(this).find('i').toggleClass('flip');
      })
      $("<i/>",{class:'fas fa-angle-up fa-lg float-right animation'}).appendTo(title)
      list = $("<ul/>",{id:'sentieri-legend'}).appendTo(container);
      return container;
    }
  })
  startView = L.Control.extend({
    options: { position: 'topleft'},
    onAdd: function (map) {
      var container = L.DomUtil.create('div', 'extentControl leaflet-bar leaflet-control leaflet-touch');
      btn=$("<a/>",{href:'#'}).appendTo(container);
      $("<i/>",{class:'fas fa-home'}).appendTo(btn)
      btn.on('click', function () {map.fitBounds(punti.getBounds());});
      return container;
    }
  })

  map.addControl(new legend());
  map.addControl(new startView());

  $.getJSON('json/punti.geojson',function (data) {
    if (!data.features) {
      map.setView(new L.LatLng(46.1220, 11.1876), 13);
    }else {
      punti = L.geoJSON(data).addTo(map).on('click',slidePanel);
      map.fitBounds(punti.getBounds());
    }
  });

  $.getJSON('json/sentieri.geojson',function (data) {
    $.each(data.features, function(i,v){
      p = v.properties
      li = $("<li/>",{text:p.nome+" ("+p.km+" km.)"}).appendTo('#sentieri-legend')
      $("<i/>",{class:'fas fa-minus fa-lg pr-2'}).css("color",p.color).prependTo(li)
    })
    sentieri = L.geoJSON(data,{
      style: function(feature) { return {color: feature.properties.color} }
    }).addTo(map)
  });

  map.setMaxBounds(map.getBounds());
}
function slidePanel(e){
  prop = e.layer.feature.properties
  $(".closePanel>h5").html(prop.nome)
  $(".poi-banner").css("background-image","url('img/"+prop.banner+"')")
  $(".poi-content").html(prop.desc)
  $('#wrapPoiInfo').fadeIn(500)
  $("body").on('click', '.closePanel', function() {
    $('#wrapPoiInfo').fadeOut(500);
  });
}
